//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertificateManagerClient.CertificateService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="CertificateService.ICertificate")]
    public interface ICertificate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICertificate/ListCertificatesInStore", ReplyAction="http://Microsoft.ServiceModel.Samples/ICertificate/ListCertificatesInStoreRespons" +
            "e")]
        System.Security.Cryptography.X509Certificates.X509Certificate2[] ListCertificatesInStore(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICertificate/ListCertificatesInRemoteStore", ReplyAction="http://Microsoft.ServiceModel.Samples/ICertificate/ListCertificatesInRemoteStoreR" +
            "esponse")]
        System.Security.Cryptography.X509Certificates.X509Certificate2[] ListCertificatesInRemoteStore(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation, string serverName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICertificate/ListExpiringCertificatesInStor" +
            "e", ReplyAction="http://Microsoft.ServiceModel.Samples/ICertificate/ListExpiringCertificatesInStor" +
            "eResponse")]
        System.Security.Cryptography.X509Certificates.X509Certificate2[] ListExpiringCertificatesInStore(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation, int days);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICertificate/ListExpiringCertificatesInRemo" +
            "teStore", ReplyAction="http://Microsoft.ServiceModel.Samples/ICertificate/ListExpiringCertificatesInRemo" +
            "teStoreResponse")]
        System.Security.Cryptography.X509Certificates.X509Certificate2[] ListExpiringCertificatesInRemoteStore(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation, int days, string serverName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICertificate/PrintCertificateInfo", ReplyAction="http://Microsoft.ServiceModel.Samples/ICertificate/PrintCertificateInfoResponse")]
        void PrintCertificateInfo(System.Security.Cryptography.X509Certificates.X509Certificate2 certificate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICertificate/EnumCertificatesByStoreName", ReplyAction="http://Microsoft.ServiceModel.Samples/ICertificate/EnumCertificatesByStoreNameRes" +
            "ponse")]
        void EnumCertificatesByStoreName(System.Security.Cryptography.X509Certificates.StoreName name, System.Security.Cryptography.X509Certificates.StoreLocation location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICertificate/EnumCertificates", ReplyAction="http://Microsoft.ServiceModel.Samples/ICertificate/EnumCertificatesResponse")]
        void EnumCertificates(string name, System.Security.Cryptography.X509Certificates.StoreLocation location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICertificate/InstallCertificateLocal", ReplyAction="http://Microsoft.ServiceModel.Samples/ICertificate/InstallCertificateLocalRespons" +
            "e")]
        bool InstallCertificateLocal(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation, System.Security.Cryptography.X509Certificates.X509Certificate2 certificate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICertificate/InstallCertificateRemote", ReplyAction="http://Microsoft.ServiceModel.Samples/ICertificate/InstallCertificateRemoteRespon" +
            "se")]
        bool InstallCertificateRemote(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation, System.Security.Cryptography.X509Certificates.X509Certificate2 certificate, string serverName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICertificate/DeleteCertificate", ReplyAction="http://Microsoft.ServiceModel.Samples/ICertificate/DeleteCertificateResponse")]
        bool DeleteCertificate(string certificateName, string storeName, System.Security.Cryptography.X509Certificates.StoreLocation location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICertificate/DeleteCertificateRemote", ReplyAction="http://Microsoft.ServiceModel.Samples/ICertificate/DeleteCertificateRemoteRespons" +
            "e")]
        bool DeleteCertificateRemote(string certificateName, string storeName, System.Security.Cryptography.X509Certificates.StoreLocation location, string serverName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICertificate/DeleteCertificateByThumbprint", ReplyAction="http://Microsoft.ServiceModel.Samples/ICertificate/DeleteCertificateByThumbprintR" +
            "esponse")]
        bool DeleteCertificateByThumbprint(string certificateName, string thumbprint, string storeName, System.Security.Cryptography.X509Certificates.StoreLocation location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICertificate/DeleteCertificateByThumbprintR" +
            "emote", ReplyAction="http://Microsoft.ServiceModel.Samples/ICertificate/DeleteCertificateByThumbprintR" +
            "emoteResponse")]
        bool DeleteCertificateByThumbprintRemote(string thumbprint, string storeName, System.Security.Cryptography.X509Certificates.StoreLocation location, string serverName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICertificate/RemoveCertificateLocal", ReplyAction="http://Microsoft.ServiceModel.Samples/ICertificate/RemoveCertificateLocalResponse" +
            "")]
        bool RemoveCertificateLocal(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation, System.Security.Cryptography.X509Certificates.X509Certificate2 certificate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICertificate/CompareCertificatesInStore", ReplyAction="http://Microsoft.ServiceModel.Samples/ICertificate/CompareCertificatesInStoreResp" +
            "onse")]
        System.Security.Cryptography.X509Certificates.X509Certificate2[] CompareCertificatesInStore(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation, string serverA, string serverB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICertificate/GetData", ReplyAction="http://Microsoft.ServiceModel.Samples/ICertificate/GetDataResponse")]
        string GetData(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICertificateChannel : CertificateManagerClient.CertificateService.ICertificate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CertificateClient : System.ServiceModel.ClientBase<CertificateManagerClient.CertificateService.ICertificate>, CertificateManagerClient.CertificateService.ICertificate {
        
        public CertificateClient() {
        }
        
        public CertificateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CertificateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CertificateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CertificateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Security.Cryptography.X509Certificates.X509Certificate2[] ListCertificatesInStore(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation) {
            return base.Channel.ListCertificatesInStore(storeName, storeLocation);
        }
        
        public System.Security.Cryptography.X509Certificates.X509Certificate2[] ListCertificatesInRemoteStore(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation, string serverName) {
            return base.Channel.ListCertificatesInRemoteStore(storeName, storeLocation, serverName);
        }
        
        public System.Security.Cryptography.X509Certificates.X509Certificate2[] ListExpiringCertificatesInStore(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation, int days) {
            return base.Channel.ListExpiringCertificatesInStore(storeName, storeLocation, days);
        }
        
        public System.Security.Cryptography.X509Certificates.X509Certificate2[] ListExpiringCertificatesInRemoteStore(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation, int days, string serverName) {
            return base.Channel.ListExpiringCertificatesInRemoteStore(storeName, storeLocation, days, serverName);
        }
        
        public void PrintCertificateInfo(System.Security.Cryptography.X509Certificates.X509Certificate2 certificate) {
            base.Channel.PrintCertificateInfo(certificate);
        }
        
        public void EnumCertificatesByStoreName(System.Security.Cryptography.X509Certificates.StoreName name, System.Security.Cryptography.X509Certificates.StoreLocation location) {
            base.Channel.EnumCertificatesByStoreName(name, location);
        }
        
        public void EnumCertificates(string name, System.Security.Cryptography.X509Certificates.StoreLocation location) {
            base.Channel.EnumCertificates(name, location);
        }
        
        public bool InstallCertificateLocal(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation, System.Security.Cryptography.X509Certificates.X509Certificate2 certificate) {
            return base.Channel.InstallCertificateLocal(storeName, storeLocation, certificate);
        }
        
        public bool InstallCertificateRemote(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation, System.Security.Cryptography.X509Certificates.X509Certificate2 certificate, string serverName) {
            return base.Channel.InstallCertificateRemote(storeName, storeLocation, certificate, serverName);
        }
        
        public bool DeleteCertificate(string certificateName, string storeName, System.Security.Cryptography.X509Certificates.StoreLocation location) {
            return base.Channel.DeleteCertificate(certificateName, storeName, location);
        }
        
        public bool DeleteCertificateRemote(string certificateName, string storeName, System.Security.Cryptography.X509Certificates.StoreLocation location, string serverName) {
            return base.Channel.DeleteCertificateRemote(certificateName, storeName, location, serverName);
        }
        
        public bool DeleteCertificateByThumbprint(string certificateName, string thumbprint, string storeName, System.Security.Cryptography.X509Certificates.StoreLocation location) {
            return base.Channel.DeleteCertificateByThumbprint(certificateName, thumbprint, storeName, location);
        }
        
        public bool DeleteCertificateByThumbprintRemote(string thumbprint, string storeName, System.Security.Cryptography.X509Certificates.StoreLocation location, string serverName) {
            return base.Channel.DeleteCertificateByThumbprintRemote(thumbprint, storeName, location, serverName);
        }
        
        public bool RemoveCertificateLocal(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation, System.Security.Cryptography.X509Certificates.X509Certificate2 certificate) {
            return base.Channel.RemoveCertificateLocal(storeName, storeLocation, certificate);
        }
        
        public System.Security.Cryptography.X509Certificates.X509Certificate2[] CompareCertificatesInStore(string storeName, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation, string serverA, string serverB) {
            return base.Channel.CompareCertificatesInStore(storeName, storeLocation, serverA, serverB);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
    }
}
